### ISSUE TITLE
Use the empty space in the hemocenters screen

### ISSUE THREAD

**Issue by kistgab** [joseiedo/doevida#7]
You have a lot of white space and there's a huge scrool at this screen: https://doevida.vercel.app/hemocentros.
I think you could use better the empty space changing the list from flex to a grid one or even having a filter for the Brazil's region.

**Comment by joseiedo** [comment]
I'm still working on this section (you can see is not even totally linked yet), the issue https://github.com/joseiedo/doevida/issues/3 was only for the scrapping part and to have just a base UI. There is already a [figma](https://www.figma.com/file/RnzKxEWReYsoGyTEZ7yGif/Doevida?type=design&node-id=7533-677&mode=design&t=cLkdXTII6DiUoMeF-0) that i'm building for this too.
But thank you for your suggestion anyway :)

**Comment by kistgab** [comment]
Sure, I thought it was the final version.
Your prototype in Figma is very beautiful btw.
It's a very important topic, it can save many people's lives.
